### ISSUE TITLE
Provide option to avoid scanning extensions on  VS Code startup

### ISSUE THREAD

**Issue by overtomanu** [sand-security/extensiontotal-vscode#10]
This extension starts scanning extensions each time when I launch VS Code. It sometimes says free limit is exhausted and repeatedly shows it in the notification area (possibly for each remaining extension). I have around 160 extensions installed, so will I hit rate limit even if I scan once in 4 days?

So when I set that scan extension every 72 hours or every 100 hours, it should scan only once in 100 hours and not on VS Code startup.

VS Code info:
Version: 1.90.1
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
Date: 2024-06-11T21:02:43.666Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.8.11-200.fc39.x86_64

ExtensionTotal:
v1.2.5

**Comment by marknuzz** [comment]
Agree, this needs to be configurable, otherwise it undermines the credibility of the author's bombshell blog posts as it can be seen as a huckster pitch (like so many of the other blog posts on a particular tech forum it was promoted on). I'd gladly pay a few dollars if this was configurable, but not $99 a month.

**Comment by amitassaraf** [comment]
@marknuzz @overtomanu I added a new config option in the latest version 1.2.8

**Comment by marknuzz** [comment]
@amitassaraf Where's the commit / release tag?

**Comment by amitassaraf** [comment]
@marknuzz Sorry we released without pushing to git initially, its here - https://github.com/sand-security/extensiontotal-vscode/commit/d8c2f38d2b465369ff279ec7f9ac08ba3f538bf7
