### ISSUE TITLE
Why Cannot I scan ExtensionTotal extension itself?

### ISSUE THREAD

**Issue by zioalex** [sand-security/extensiontotal-vscode#2]
Hi there,
just to be sure that your extension is safe I tried to scan it...
But it doesn't work
![image](https://github.com/sand-security/extensiontotal-vscode/assets/3593840/ab7566db-fb9a-491c-a24b-5aad56372def)
![image](https://github.com/sand-security/extensiontotal-vscode/assets/3593840/848f7ae5-dd62-4744-953a-c9a786a96895)

Not to say that you are fake...But why it doesn't work?

**Comment by amitassaraf** [comment]
Hey @zioalex, you can, if you search for it in the home page it shows up - https://app.extensiontotal.com/report/extensiontotal.extensiontotal-vscode

We are still waiting for domain verification so the report is not ideal yet, once its approved ExtensionTotal should be low per the engine

**Comment by zioalex** [comment]
Cool thanks,
It wasn't there when I tried.
