### ISSUE TITLE
[Feature Request] Show progress in bottom status bar instead of as notifications

### ISSUE THREAD

**Issue by brandoningli** [sand-security/extensiontotal-vscode#4]
Currently, the extension shows a series of notifications upon startup when checking extensions. This would probably be better rendered as an item on the bottom status bar to avoid distraction and clutter on startup.

**Comment by mikeburgh** [comment]
You could also use the native VSCode progress bar feature for a single notification: vscode.window.withProgress

**Comment by amitassaraf** [comment]
@brandoningli @mikeburgh Thanks for the recommendation, we are working on it now.

**Comment by amitassaraf** [comment]
@brandoningli @mikeburgh We've released a new version with these changes.
