### ISSUE TITLE
[Feature Request] Smarter Scan Intervals

### ISSUE THREAD

**Issue by brandoningli** [sand-security/extensiontotal-vscode#5]
Instead of naively checking every extension on every VSCode startup, it would be nice to more smartly limit how often the scan is run. Some ideas include

- An option to scan extensions a maximum of once every `x` hours.
- An option to only re-scan extensions when a new version is installed or available.

**Comment by amitassaraf** [comment]
@brandoningli Hey! Great suggestion, we will add that this week!

**Comment by amitassaraf** [comment]
@brandoningli We've released a new version with this changes.

**Comment by brandoningli** [comment]
I looks like the scan interval value is never actually used, but rather a hard-coded 3 hour value is.
