### ISSUE TITLE
Data leakage and other threats.

### ISSUE THREAD

**Issue by alanhoyle** [sand-security/extensiontotal-vscode#6]
Hey all, an issue here is that this leaks information about a VSCode installation to you all, an unknown third party.  

The extension leaks: 

1. The IP address of anyone running the extension
2. The list of all extensions that are running at that IP address

Your server becomes a place that a nefarious entity would want to attack and this data could be valuable to an adversary.  

It might be better if you modified your APIs to send some kind of fingerprint database back to the user which could be used **on the client side** to determine the threat level of the installed extensions.  

I.e I imagine you could implement [k-anonymity](https://en.wikipedia.org/wiki/K-anonymity) like the way that the [the "Have I Been Pwned" password checker](https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/#cloudflareprivacyandkanonymity) works.  You could take the SHA hash of the extension with the extension version (salted maybe?), truncate down to the first 2 hex digits (the "prefix"), and then return all matches in your database that have the same prefix.  The returned values would include the remaining hash (suffixes) of all matches along with a couple bytes to explain the level of vulnerability.  

I picked a 2 digit prefix as you all claim that there are only ~60K extensions, and 4 hex digits could potentially be unique for all of them, ignoring extension versions.  3 digits might allow k-anonymity, but you'd have more likelihood of extensions with no collisions, but I'm not an expert and you'd have to run the hashes on the full list of extensions/versions to confirm this.  

With something like that, at least you'd no longer necessarily be leaking the list of all extensions installed at a particular IP has installed.  

Another issue is that this git repo becomes a target as now someone will want to insert a backdoor into the code to gain access to the paranoid VSCode users.

**Comment by amitassaraf** [comment]
@alanhoyle Thanks for the feedback! We do not save any IP addresses or lists of extensions that a certain IP address or API key has queried. 

Regarding this extension being open-source, it is for transparency, we do not plan on allowing external PRs or commits.
