### ISSUE TITLE
Seems to have a stale list of installed/enabled plugins

### ISSUE THREAD

**Issue by EkwzY9PwoKqa7FnPGga6xDigKst3jGmobXnyLAF** [sand-security/extensiontotal-vscode#7]
I installed, gave it the API key, it scanned, came back with results. I then uninstalled a few of the extensions, closed VSC, reopened, it scanned again, the results look identical.

I uninstalled the ExtensionTotal extension, restarted VSC, re-installed it (no prompt for API Key) and the same set of results.

after uninstall, the folder "extensiontotal.extensiontotal-vscode-1.2.4" was still in "%USERPROFILE%\.vscode\extensions" so I removed that folder, restarted VSC and reinstalled the extension. in Settings, the User still had my API Key value and the results are still the same.

**Comment by amitassaraf** [comment]
Hey @EkwzY9PwoKqa7FnPGga6xDigKst3jGmobXnyLAF This is fixed in the latest version 1.2.5, each time a scan is ran, it removes all previous results to create a clean scan.
