### ISSUE TITLE
Listed extensions are selectable but nothing informative shows up

### ISSUE THREAD

**Issue by itaibh** [sand-security/extensiontotal-vscode#9]
![image](https://github.com/sand-security/extensiontotal-vscode/assets/140983/09f36979-8e05-435c-bc3f-fed1bf181e7f)

I installed the extension, entered the API key and the extension started scanning. While it was scanning I tried clicking on found extensions, expecting to see more details about them, but nothing. I let the scan finish. Tried again, still nothing. Tried restarting VSCode, still nothing.

So currently this extension is usefull in telling me the risk factor of each extension but then I have to go manually to https://www.extensiontotal.com/ and search for each extension, which might be the wrong one, because extensions can have similar names. And it's also cumbersome.

I'm using version 1.2.4 of the extension with VSCode version 1.90.2 on Ubuntu Linux 24.04.

Please fix it :pray:

**Comment by amitassaraf** [comment]
Hey @itaibh This is fixed in the latest version 1.2.5, when clicking on an extension it will direct you to the corresponding report.
